import streamlit as st
import pandas as pd
import plotly.express as px

# Set Page Config for Mobile
# NOTE: set_page_config must be called before any other Streamlit UI calls.
st.set_page_config(page_title="CFB/Madden Film Room", layout="wide")

st.title("🏈 Scheme Lab: Film Review")

# Improved Data Loading Section
uploaded_file = st.file_uploader("Upload your stats.csv file", type="csv")

if uploaded_file:
    try:
        # Try reading with common encodings if default fails
        df = pd.read_csv(uploaded_file)
        
        if df.empty:
            st.warning("⚠️ The uploaded file is empty. Please check your Colab output.")
            st.stop()
            
    except Exception as e:
        st.error(f"❌ Error reading CSV: {e}")
        st.info("Tip: Make sure the file was downloaded correctly from your Google Colab session.")
        st.stop()
else:
    st.info("📢 Please upload the 'stats.csv' file generated by your Colab script.")
    st.stop()


# Defensive: coerce numeric fields and fill/handle missing values
for col in ['Down', 'Distance', 'Yards Gained']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Replace NaNs with safe defaults (you might want to handle differently)
df['Down'] = df['Down'].fillna(1).astype(int)
df['Distance'] = df['Distance'].fillna(0).astype(float)
df['Yards Gained'] = df['Yards Gained'].fillna(0).astype(float)

# 2. Success Logic Formula
def check_success(row):
    # returns boolean
    down = int(row['Down'])
    distance = row['Distance']
    gained = row['Yards Gained']
    if down == 1:
        return gained >= (distance * 0.5)
    if down == 2:
        return gained >= (distance * 0.7)
    return gained >= distance

df['Success'] = df.apply(check_success, axis=1)

# 3. Mobile-Friendly Metrics
col1, col2, col3 = st.columns(3)
success_rate = (df['Success'].sum() / max(len(df), 1)) * 100
col1.metric("Overall Success Rate", f"{success_rate:.1f}%")
col2.metric("Avg Yards / Play", f"{df['Yards Gained'].mean():.1f}")

# Provide a quick best/worst formation snapshot
formation_stats = df.groupby('Formation')['Success'].mean().sort_values(ascending=False)
if not formation_stats.empty:
    best = formation_stats.index[0]
    worst = formation_stats.index[-1]
    col3.metric("Best Formation", best, delta=f"{formation_stats.iloc[0]*100:.0f}%")
else:
    col3.metric("Best Formation", "N/A")

# 4. Scheme Analysis (Charts)
st.subheader("Scheme Efficiency by Formation")
form_success = (
    df.groupby('Formation')['Success']
    .mean()
    .reset_index()
    .rename(columns={'Success': 'SuccessPct'})
)
# convert to percent
form_success['SuccessPct'] = form_success['SuccessPct'] * 100

fig = px.bar(
    form_success,
    x='Formation',
    y='SuccessPct',
    color='Formation',
    labels={'SuccessPct': 'Success %'},
    height=300
)
fig.update_yaxes(range=[0, 100], ticksuffix='%')
st.plotly_chart(fig, use_container_width=True)

# 5. The "Film Table"
st.subheader("Play-by-Play Review")
# Filter by formation on mobile
selected_form = st.selectbox("Filter by Formation", options=['All'] + sorted(df['Formation'].unique()))
filtered_df = df if selected_form == 'All' else df[df['Formation'] == selected_form]

# Helper to render link/button compatibly across Streamlit versions
def render_link(label: str, url: str):
    if hasattr(st, "link_button"):
        try:
            st.link_button(label, url)
            return
        except Exception:
            pass
    # Fallback: render a markdown link (will open in same tab in many setups)
    # Use an HTML anchor to try to open in a new tab if your Streamlit allows unsafe HTML
    try:
        st.markdown(f'<a href="{url}" target="_blank" rel="noopener noreferrer">{label}</a>', unsafe_allow_html=True)
    except TypeError:
        # older/newer streamlit may reject unsafe_allow_html param - fall back to plain markdown
        st.markdown(f"[{label}]({url})")

# Displaying the data (use itertuples for slightly better performance)
for r in filtered_df.itertuples(index=False):
    formation = getattr(r, "Formation", "")
    # pandas converts invalid identifier chars (like spaces) to underscores for namedtuple fields
    play_name = getattr(r, "Play_Name", getattr(r, "Play Name", ""))
    success_sym = "✅" if getattr(r, "Success", False) else "❌"
    down = getattr(r, "Down", "")
    distance = getattr(r, "Distance", "")
    yards = getattr(r, "Yards_Gained", getattr(r, "Yards Gained", ""))
    link = getattr(r, "Twitch_Link", "")
    with st.expander(f"{formation} - {play_name} ({success_sym})"):
        st.write(f"**Situation:** {down} & {distance}")
        st.write(f"**Gain:** {yards} yards")
        render_link("Watch Clip", link)
